version: 2
jobs:
  build:
    working_directory: ~/pk-test
    docker:
      - image: ucreateit/php7.2:v0.2
      - image: ucreateit/laravel-pgsql:0.0.1
        environment:
        DATABASE_URL: postgres://ubuntu@localhost:5432/postgres
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update && sudo apt-get -f install && sudo apt-get install wget
      - run: 
          name: Install Composer
          command: |
            sudo composer self-update
            composer install --prefer-source --no-interaction --dev
      
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "b56:a5:00:99:c8:3a:88:23:81:40:2f:db:4e:77:d9:fc"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
            fi